name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: RoHiT-48566

          template: classic
          base: header, activity, repositories, community

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_followup: yes
          plugin_stars: yes

          config_timezone: Asia/Kolkata
          filename: github-metrics.svg
